/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_Bearers_SubjectToStatusTransfer_ItemIEs_H_
#define	_Bearers_SubjectToStatusTransfer_ItemIEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ID.h"
#include "Criticality.h"
#include "Bearers-SubjectToStatusTransfer-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bearers-SubjectToStatusTransfer-ItemIEs */
typedef struct Bearers_SubjectToStatusTransfer_ItemIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	Bearers_SubjectToStatusTransfer_Item_t	 bearse;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Bearers_SubjectToStatusTransfer_ItemIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Bearers_SubjectToStatusTransfer_ItemIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_Bearers_SubjectToStatusTransfer_ItemIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_Bearers_SubjectToStatusTransfer_ItemIEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Bearers_SubjectToStatusTransfer_ItemIEs_H_ */
#include <asn_internal.h>
