/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_Bearers_SubjectToStatusTransfer_Item_H_
#define	_Bearers_SubjectToStatusTransfer_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-ID.h"
#include "COUNTvalue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bearers-SubjectToStatusTransfer-Item */
typedef struct Bearers_SubjectToStatusTransfer_Item {
	E_RAB_ID_t	 e_RAB_ID;
	COUNTvalue_t	 ul_CountValue;
	COUNTvalue_t	 dl_CountValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Bearers_SubjectToStatusTransfer_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Bearers_SubjectToStatusTransfer_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_Bearers_SubjectToStatusTransfer_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_Bearers_SubjectToStatusTransfer_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Bearers_SubjectToStatusTransfer_Item_H_ */
#include <asn_internal.h>
