/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_E_RABAdmittedList_H_
#define	_E_RABAdmittedList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_RABAdmittedItemIEs;

/* E-RABAdmittedList */
typedef struct E_RABAdmittedList {
	A_SEQUENCE_OF(struct E_RABAdmittedItemIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_RABAdmittedList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_RABAdmittedList;
extern asn_SET_OF_specifics_t asn_SPC_E_RABAdmittedList_specs_1;
extern asn_TYPE_member_t asn_MBR_E_RABAdmittedList_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "E-RABAdmittedItemIEs.h"

#endif	/* _E_RABAdmittedList_H_ */
#include <asn_internal.h>
