/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_E_UERadioCapability_H_
#define	_E_UERadioCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E-UERadioCapability */
typedef OCTET_STRING_t	 E_UERadioCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_UERadioCapability;
asn_struct_free_f E_UERadioCapability_free;
asn_struct_print_f E_UERadioCapability_print;
asn_constr_check_f E_UERadioCapability_constraint;
ber_type_decoder_f E_UERadioCapability_decode_ber;
der_type_encoder_f E_UERadioCapability_encode_der;
xer_type_decoder_f E_UERadioCapability_decode_xer;
xer_type_encoder_f E_UERadioCapability_encode_xer;
oer_type_decoder_f E_UERadioCapability_decode_oer;
oer_type_encoder_f E_UERadioCapability_encode_oer;
per_type_decoder_f E_UERadioCapability_decode_uper;
per_type_encoder_f E_UERadioCapability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_UERadioCapability_H_ */
#include <asn_internal.h>
