/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_HandoverRequest_IEs_H_
#define	_HandoverRequest_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "HandoverType-Item.h"
#include "Cause-Item.h"
#include "UE-Aggregate-Maxbitrate-Item.h"
#include "E-RABToBeSetupListHOReq-Item.h"
#include "Source-To-Target-TContainer-Item.h"
#include "UESecurityCapabilities-Item.h"
#include "SecurityContext-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HandoverRequest-IEs */
typedef struct HandoverRequest_IEs {
	MME_Item_t	 mme;
	HandoverType_Item_t	 type;
	Cause_Item_t	 cause;
	UE_Aggregate_Maxbitrate_Item_t	 bitrate;
	E_RABToBeSetupListHOReq_Item_t	 horeq;
	Source_To_Target_TContainer_Item_t	 container;
	UESecurityCapabilities_Item_t	 secCap;
	SecurityContext_Item_t	 secContext;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverRequest_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HandoverRequest_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_HandoverRequest_IEs_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverRequest_IEs_H_ */
#include <asn_internal.h>
