/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_MMEStatusTransfer_IEs_H_
#define	_MMEStatusTransfer_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "ENUB-Item.h"
#include "ENB-StatusTransfer-TransparentContainer-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MMEStatusTransfer-IEs */
typedef struct MMEStatusTransfer_IEs {
	MME_Item_t	 mme;
	ENUB_Item_t	 enub;
	ENB_StatusTransfer_TransparentContainer_Item_t	 status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MMEStatusTransfer_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MMEStatusTransfer_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MMEStatusTransfer_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_MMEStatusTransfer_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MMEStatusTransfer_IEs_H_ */
#include <asn_internal.h>
