/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_MMEStatusTransfer_H_
#define	_MMEStatusTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MMEStatusTransfer-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MMEStatusTransfer */
typedef struct MMEStatusTransfer {
	MMEStatusTransfer_IEs_t	 protocolIEs;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MMEStatusTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MMEStatusTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_MMEStatusTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_MMEStatusTransfer_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _MMEStatusTransfer_H_ */
#include <asn_internal.h>
