/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_Source_To_Target_TContainer_H_
#define	_Source_To_Target_TContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Source-To-Target-TContainer */
typedef OCTET_STRING_t	 Source_To_Target_TContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Source_To_Target_TContainer;
asn_struct_free_f Source_To_Target_TContainer_free;
asn_struct_print_f Source_To_Target_TContainer_print;
asn_constr_check_f Source_To_Target_TContainer_constraint;
ber_type_decoder_f Source_To_Target_TContainer_decode_ber;
der_type_encoder_f Source_To_Target_TContainer_encode_der;
xer_type_decoder_f Source_To_Target_TContainer_decode_xer;
xer_type_encoder_f Source_To_Target_TContainer_encode_xer;
oer_type_decoder_f Source_To_Target_TContainer_decode_oer;
oer_type_encoder_f Source_To_Target_TContainer_encode_oer;
per_type_decoder_f Source_To_Target_TContainer_decode_uper;
per_type_encoder_f Source_To_Target_TContainer_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Source_To_Target_TContainer_H_ */
#include <asn_internal.h>
