/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_TAI_H_
#define	_TAI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "TAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TAI */
typedef struct TAI {
	PLMNidentity_t	 pLMNidentity;
	TAC_t	 tAC;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TAI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TAI;
extern asn_SEQUENCE_specifics_t asn_SPC_TAI_specs_1;
extern asn_TYPE_member_t asn_MBR_TAI_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TAI_H_ */
#include <asn_internal.h>
