/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_TargeteNB_ID_H_
#define	_TargeteNB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Global-ENB-ID.h"
#include "TAI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TargeteNB-ID */
typedef struct TargeteNB_ID {
	Global_ENB_ID_t	 global_ENB_ID;
	TAI_t	 selected_TAI;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargeteNB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargeteNB_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_TargeteNB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargeteNB_ID_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TargeteNB_ID_H_ */
#include <asn_internal.h>
