/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_TargetID_H_
#define	_TargetID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TargeteNB-ID.h"
#include "TargetRNC-ID.h"
#include "CGI.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TargetID_PR {
	TargetID_PR_NOTHING,	/* No components present */
	TargetID_PR_targeteNB_ID,
	TargetID_PR_targetRNC_ID,
	TargetID_PR_cGI
} TargetID_PR;

/* TargetID */
typedef struct TargetID {
	TargetID_PR present;
	union TargetID_u {
		TargeteNB_ID_t	 targeteNB_ID;
		TargetRNC_ID_t	 targetRNC_ID;
		CGI_t	 cGI;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetID;
extern asn_CHOICE_specifics_t asn_SPC_TargetID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargetID_1[3];
extern asn_per_constraints_t asn_PER_type_TargetID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TargetID_H_ */
#include <asn_internal.h>
