/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_UeContextReleaseComplete_H_
#define	_UeContextReleaseComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UeContextReleaseComplete-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UeContextReleaseComplete */
typedef struct UeContextReleaseComplete {
	UeContextReleaseComplete_IEs_t	 protocolIEs;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UeContextReleaseComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UeContextReleaseComplete;
extern asn_SEQUENCE_specifics_t asn_SPC_UeContextReleaseComplete_specs_1;
extern asn_TYPE_member_t asn_MBR_UeContextReleaseComplete_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UeContextReleaseComplete_H_ */
#include <asn_internal.h>
