/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#include "Bearers-SubjectToStatusTransferList.h"

asn_TYPE_member_t asn_MBR_Bearers_SubjectToStatusTransferList_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Bearers_SubjectToStatusTransfer_ItemIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Bearers_SubjectToStatusTransferList_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_Bearers_SubjectToStatusTransferList_specs_1 = {
	sizeof(struct Bearers_SubjectToStatusTransferList),
	offsetof(struct Bearers_SubjectToStatusTransferList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_Bearers_SubjectToStatusTransferList = {
	"Bearers-SubjectToStatusTransferList",
	"Bearers-SubjectToStatusTransferList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Bearers_SubjectToStatusTransferList_tags_1,
	sizeof(asn_DEF_Bearers_SubjectToStatusTransferList_tags_1)
		/sizeof(asn_DEF_Bearers_SubjectToStatusTransferList_tags_1[0]), /* 1 */
	asn_DEF_Bearers_SubjectToStatusTransferList_tags_1,	/* Same as above */
	sizeof(asn_DEF_Bearers_SubjectToStatusTransferList_tags_1)
		/sizeof(asn_DEF_Bearers_SubjectToStatusTransferList_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_Bearers_SubjectToStatusTransferList_1,
	1,	/* Single element */
	&asn_SPC_Bearers_SubjectToStatusTransferList_specs_1	/* Additional specs */
};

