/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_CGI_H_
#define	_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "LAC.h"
#include "CI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CGI */
typedef struct CGI {
	PLMNidentity_t	 pLMNidentity;
	LAC_t	 lAC;
	CI_t	 cI;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CGI;
extern asn_SEQUENCE_specifics_t asn_SPC_CGI_specs_1;
extern asn_TYPE_member_t asn_MBR_CGI_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CGI_H_ */
#include <asn_internal.h>
