/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#include "COUNTvalue.h"

asn_TYPE_member_t asn_MBR_COUNTvalue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct COUNTvalue, pDCP_SN),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDCP_SN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDCP-SN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COUNTvalue, hFN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HFN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hFN"
		},
};
static const ber_tlv_tag_t asn_DEF_COUNTvalue_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_COUNTvalue_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pDCP-SN */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* hFN */
};
asn_SEQUENCE_specifics_t asn_SPC_COUNTvalue_specs_1 = {
	sizeof(struct COUNTvalue),
	offsetof(struct COUNTvalue, _asn_ctx),
	asn_MAP_COUNTvalue_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_COUNTvalue = {
	"COUNTvalue",
	"COUNTvalue",
	&asn_OP_SEQUENCE,
	asn_DEF_COUNTvalue_tags_1,
	sizeof(asn_DEF_COUNTvalue_tags_1)
		/sizeof(asn_DEF_COUNTvalue_tags_1[0]), /* 1 */
	asn_DEF_COUNTvalue_tags_1,	/* Same as above */
	sizeof(asn_DEF_COUNTvalue_tags_1)
		/sizeof(asn_DEF_COUNTvalue_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_COUNTvalue_1,
	2,	/* Elements count */
	&asn_SPC_COUNTvalue_specs_1	/* Additional specs */
};

