/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_E_RABToBeSetupListHOReq_H_
#define	_E_RABToBeSetupListHOReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_RABToBeSetupItemHOReqIEs;

/* E-RABToBeSetupListHOReq */
typedef struct E_RABToBeSetupListHOReq {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemHOReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_RABToBeSetupListHOReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_RABToBeSetupListHOReq;
extern asn_SET_OF_specifics_t asn_SPC_E_RABToBeSetupListHOReq_specs_1;
extern asn_TYPE_member_t asn_MBR_E_RABToBeSetupListHOReq_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "E-RABToBeSetupItemHOReqIEs.h"

#endif	/* _E_RABToBeSetupListHOReq_H_ */
#include <asn_internal.h>
