/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_ENUB_Item_H_
#define	_ENUB_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ID.h"
#include "Criticality.h"
#include "ENB-UE-S1AP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ENUB-Item */
typedef struct ENUB_Item {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	ENB_UE_S1AP_ID_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ENUB_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ENUB_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ENUB_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ENUB_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ENUB_Item_H_ */
#include <asn_internal.h>
