/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_HandoverNotify_IEs_H_
#define	_HandoverNotify_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "ENUB-Item.h"
#include "EUTRAN-Item.h"
#include "TAI-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HandoverNotify-IEs */
typedef struct HandoverNotify_IEs {
	MME_Item_t	 mme;
	ENUB_Item_t	 enub;
	EUTRAN_Item_t	 eutran;
	TAI_Item_t	 tai;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverNotify_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverNotify_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HandoverNotify_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_HandoverNotify_IEs_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverNotify_IEs_H_ */
#include <asn_internal.h>
