/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_HandoverRequired_IEs_H_
#define	_HandoverRequired_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "ENUB-Item.h"
#include "HandoverType-Item.h"
#include "Cause-Item.h"
#include "TargetID-Item.h"
#include "Source-To-Target-TContainer-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HandoverRequired-IEs */
typedef struct HandoverRequired_IEs {
	MME_Item_t	 mme;
	ENUB_Item_t	 enub;
	HandoverType_Item_t	 type;
	Cause_Item_t	 cause;
	TargetID_Item_t	 target;
	Source_To_Target_TContainer_Item_t	 container;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverRequired_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverRequired_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HandoverRequired_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_HandoverRequired_IEs_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverRequired_IEs_H_ */
#include <asn_internal.h>
