/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#include "InitialContextSetupRequest-IEs.h"

asn_TYPE_member_t asn_MBR_InitialContextSetupRequest_IEs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextSetupRequest_IEs, mme),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mme"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextSetupRequest_IEs, enub),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ENUB_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enub"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextSetupRequest_IEs, bitrate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Aggregate_Maxbitrate_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bitrate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextSetupRequest_IEs, sureq),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_RABToBeSetupListCtxtSUReq_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sureq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextSetupRequest_IEs, secCap),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UESecurityCapabilities_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"secCap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialContextSetupRequest_IEs, secKey),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SecurityKey_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"secKey"
		},
};
static const ber_tlv_tag_t asn_DEF_InitialContextSetupRequest_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitialContextSetupRequest_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mme */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* enub */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bitrate */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sureq */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* secCap */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* secKey */
};
asn_SEQUENCE_specifics_t asn_SPC_InitialContextSetupRequest_IEs_specs_1 = {
	sizeof(struct InitialContextSetupRequest_IEs),
	offsetof(struct InitialContextSetupRequest_IEs, _asn_ctx),
	asn_MAP_InitialContextSetupRequest_IEs_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitialContextSetupRequest_IEs = {
	"InitialContextSetupRequest-IEs",
	"InitialContextSetupRequest-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_InitialContextSetupRequest_IEs_tags_1,
	sizeof(asn_DEF_InitialContextSetupRequest_IEs_tags_1)
		/sizeof(asn_DEF_InitialContextSetupRequest_IEs_tags_1[0]), /* 1 */
	asn_DEF_InitialContextSetupRequest_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitialContextSetupRequest_IEs_tags_1)
		/sizeof(asn_DEF_InitialContextSetupRequest_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitialContextSetupRequest_IEs_1,
	6,	/* Elements count */
	&asn_SPC_InitialContextSetupRequest_IEs_specs_1	/* Additional specs */
};

