/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_S1AP_ELEMENTARY_PROCEDURE_H_
#define	_S1AP_ELEMENTARY_PROCEDURE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitialUeMessage.h"
#include "DownlinkNasTransport.h"
#include "UplinkNasTransport.h"
#include "InitialContextSetupRequest.h"
#include "InitialContextSetupResponse.h"
#include "UeCapabilityInfoIndication.h"
#include "HandoverRequired.h"
#include "HandoverRequest.h"
#include "HandoverRequestAcknowledge.h"
#include "HandoverCommand.h"
#include "ENBStatusTransfer.h"
#include "MMEStatusTransfer.h"
#include "HandoverNotify.h"
#include "UeContextReleaseCommand.h"
#include "UeContextReleaseComplete.h"
#include "UeContextReleaseRequest.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_ELEMENTARY_PROCEDURE_PR {
	S1AP_ELEMENTARY_PROCEDURE_PR_NOTHING,	/* No components present */
	S1AP_ELEMENTARY_PROCEDURE_PR_initialUeMessage,
	S1AP_ELEMENTARY_PROCEDURE_PR_downlinkNasTransport,
	S1AP_ELEMENTARY_PROCEDURE_PR_uplinkNasTransport,
	S1AP_ELEMENTARY_PROCEDURE_PR_initialContextSetupRequest,
	S1AP_ELEMENTARY_PROCEDURE_PR_initialContextSetupResponse,
	S1AP_ELEMENTARY_PROCEDURE_PR_ueCapabilityInfoIndication,
	S1AP_ELEMENTARY_PROCEDURE_PR_handoverRequired,
	S1AP_ELEMENTARY_PROCEDURE_PR_handoverRequest,
	S1AP_ELEMENTARY_PROCEDURE_PR_handoverRequestAck,
	S1AP_ELEMENTARY_PROCEDURE_PR_handoverCommand,
	S1AP_ELEMENTARY_PROCEDURE_PR_eNBStatusTransfer,
	S1AP_ELEMENTARY_PROCEDURE_PR_mmeStatusTransfer,
	S1AP_ELEMENTARY_PROCEDURE_PR_handoverNotify,
	S1AP_ELEMENTARY_PROCEDURE_PR_ueContextReleaseCommand,
	S1AP_ELEMENTARY_PROCEDURE_PR_ueContextReleaseComplete,
	S1AP_ELEMENTARY_PROCEDURE_PR_ueContextReleaseRequest
} S1AP_ELEMENTARY_PROCEDURE_PR;

/* S1AP-ELEMENTARY-PROCEDURE */
typedef struct S1AP_ELEMENTARY_PROCEDURE {
	S1AP_ELEMENTARY_PROCEDURE_PR present;
	union S1AP_ELEMENTARY_PROCEDURE_u {
		InitialUeMessage_t	 initialUeMessage;
		DownlinkNasTransport_t	 downlinkNasTransport;
		UplinkNasTransport_t	 uplinkNasTransport;
		InitialContextSetupRequest_t	 initialContextSetupRequest;
		InitialContextSetupResponse_t	 initialContextSetupResponse;
		UeCapabilityInfoIndication_t	 ueCapabilityInfoIndication;
		HandoverRequired_t	 handoverRequired;
		HandoverRequest_t	 handoverRequest;
		HandoverRequestAcknowledge_t	 handoverRequestAck;
		HandoverCommand_t	 handoverCommand;
		ENBStatusTransfer_t	 eNBStatusTransfer;
		MMEStatusTransfer_t	 mmeStatusTransfer;
		HandoverNotify_t	 handoverNotify;
		UeContextReleaseCommand_t	 ueContextReleaseCommand;
		UeContextReleaseComplete_t	 ueContextReleaseComplete;
		UeContextReleaseRequest_t	 ueContextReleaseRequest;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ELEMENTARY_PROCEDURE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ELEMENTARY_PROCEDURE;
extern asn_CHOICE_specifics_t asn_SPC_S1AP_ELEMENTARY_PROCEDURE_specs_1;
extern asn_TYPE_member_t asn_MBR_S1AP_ELEMENTARY_PROCEDURE_1[16];
extern asn_per_constraints_t asn_PER_type_S1AP_ELEMENTARY_PROCEDURE_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_ELEMENTARY_PROCEDURE_H_ */
#include <asn_internal.h>
