/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#include "S1AP-ELEMENTARY-PROCEDURE.h"

static asn_oer_constraints_t asn_OER_type_S1AP_ELEMENTARY_PROCEDURE_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_S1AP_ELEMENTARY_PROCEDURE_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_S1AP_ELEMENTARY_PROCEDURE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.initialUeMessage),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialUeMessage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialUeMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.downlinkNasTransport),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DownlinkNasTransport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"downlinkNasTransport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.uplinkNasTransport),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkNasTransport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkNasTransport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.initialContextSetupRequest),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialContextSetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialContextSetupRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.initialContextSetupResponse),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialContextSetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialContextSetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.ueCapabilityInfoIndication),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UeCapabilityInfoIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueCapabilityInfoIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.handoverRequired),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.handoverRequest),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.handoverRequestAck),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverRequestAck"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.handoverCommand),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverCommand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.eNBStatusTransfer),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ENBStatusTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eNBStatusTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.mmeStatusTransfer),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MMEStatusTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mmeStatusTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.handoverNotify),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandoverNotify,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverNotify"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.ueContextReleaseCommand),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UeContextReleaseCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueContextReleaseCommand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.ueContextReleaseComplete),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UeContextReleaseComplete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueContextReleaseComplete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1AP_ELEMENTARY_PROCEDURE, choice.ueContextReleaseRequest),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UeContextReleaseRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueContextReleaseRequest"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_S1AP_ELEMENTARY_PROCEDURE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialUeMessage */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* downlinkNasTransport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uplinkNasTransport */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* initialContextSetupRequest */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* initialContextSetupResponse */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ueCapabilityInfoIndication */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* handoverRequired */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* handoverRequest */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* handoverRequestAck */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* handoverCommand */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* eNBStatusTransfer */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* mmeStatusTransfer */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* handoverNotify */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* ueContextReleaseCommand */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* ueContextReleaseComplete */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 } /* ueContextReleaseRequest */
};
asn_CHOICE_specifics_t asn_SPC_S1AP_ELEMENTARY_PROCEDURE_specs_1 = {
	sizeof(struct S1AP_ELEMENTARY_PROCEDURE),
	offsetof(struct S1AP_ELEMENTARY_PROCEDURE, _asn_ctx),
	offsetof(struct S1AP_ELEMENTARY_PROCEDURE, present),
	sizeof(((struct S1AP_ELEMENTARY_PROCEDURE *)0)->present),
	asn_MAP_S1AP_ELEMENTARY_PROCEDURE_tag2el_1,
	16,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_S1AP_ELEMENTARY_PROCEDURE = {
	"S1AP-ELEMENTARY-PROCEDURE",
	"S1AP-ELEMENTARY-PROCEDURE",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_S1AP_ELEMENTARY_PROCEDURE_constr_1, &asn_PER_type_S1AP_ELEMENTARY_PROCEDURE_constr_1, CHOICE_constraint },
	asn_MBR_S1AP_ELEMENTARY_PROCEDURE_1,
	16,	/* Elements count */
	&asn_SPC_S1AP_ELEMENTARY_PROCEDURE_specs_1	/* Additional specs */
};

