/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#include "TAI.h"

asn_TYPE_member_t asn_MBR_TAI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TAI, pLMNidentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMNidentity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pLMNidentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TAI, tAC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TAC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAC"
		},
};
static const ber_tlv_tag_t asn_DEF_TAI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TAI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pLMNidentity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tAC */
};
asn_SEQUENCE_specifics_t asn_SPC_TAI_specs_1 = {
	sizeof(struct TAI),
	offsetof(struct TAI, _asn_ctx),
	asn_MAP_TAI_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TAI = {
	"TAI",
	"TAI",
	&asn_OP_SEQUENCE,
	asn_DEF_TAI_tags_1,
	sizeof(asn_DEF_TAI_tags_1)
		/sizeof(asn_DEF_TAI_tags_1[0]), /* 1 */
	asn_DEF_TAI_tags_1,	/* Same as above */
	sizeof(asn_DEF_TAI_tags_1)
		/sizeof(asn_DEF_TAI_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TAI_1,
	2,	/* Elements count */
	&asn_SPC_TAI_specs_1	/* Additional specs */
};

