/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#include "UE-Aggregate-Maxbitrate.h"

asn_TYPE_member_t asn_MBR_UE_Aggregate_Maxbitrate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_Aggregate_Maxbitrate, ue_Aggregate_MaximumBitRateDL),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Aggregate-MaximumBitRateDL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_Aggregate_Maxbitrate, ue_Aggregate_MaximumBitRateUL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Aggregate-MaximumBitRateUL"
		},
};
static const ber_tlv_tag_t asn_DEF_UE_Aggregate_Maxbitrate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_Aggregate_Maxbitrate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-Aggregate-MaximumBitRateDL */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-Aggregate-MaximumBitRateUL */
};
asn_SEQUENCE_specifics_t asn_SPC_UE_Aggregate_Maxbitrate_specs_1 = {
	sizeof(struct UE_Aggregate_Maxbitrate),
	offsetof(struct UE_Aggregate_Maxbitrate, _asn_ctx),
	asn_MAP_UE_Aggregate_Maxbitrate_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UE_Aggregate_Maxbitrate = {
	"UE-Aggregate-Maxbitrate",
	"UE-Aggregate-Maxbitrate",
	&asn_OP_SEQUENCE,
	asn_DEF_UE_Aggregate_Maxbitrate_tags_1,
	sizeof(asn_DEF_UE_Aggregate_Maxbitrate_tags_1)
		/sizeof(asn_DEF_UE_Aggregate_Maxbitrate_tags_1[0]), /* 1 */
	asn_DEF_UE_Aggregate_Maxbitrate_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_Aggregate_Maxbitrate_tags_1)
		/sizeof(asn_DEF_UE_Aggregate_Maxbitrate_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UE_Aggregate_Maxbitrate_1,
	2,	/* Elements count */
	&asn_SPC_UE_Aggregate_Maxbitrate_specs_1	/* Additional specs */
};

