/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#include "UE-S1AP-ID-pair.h"

asn_TYPE_member_t asn_MBR_UE_S1AP_ID_pair_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UE_S1AP_ID_pair, mme),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_UE_S1AP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mme"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UE_S1AP_ID_pair, enub),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ENB_UE_S1AP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enub"
		},
};
static const ber_tlv_tag_t asn_DEF_UE_S1AP_ID_pair_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UE_S1AP_ID_pair_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mme */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* enub */
};
asn_SEQUENCE_specifics_t asn_SPC_UE_S1AP_ID_pair_specs_1 = {
	sizeof(struct UE_S1AP_ID_pair),
	offsetof(struct UE_S1AP_ID_pair, _asn_ctx),
	asn_MAP_UE_S1AP_ID_pair_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UE_S1AP_ID_pair = {
	"UE-S1AP-ID-pair",
	"UE-S1AP-ID-pair",
	&asn_OP_SEQUENCE,
	asn_DEF_UE_S1AP_ID_pair_tags_1,
	sizeof(asn_DEF_UE_S1AP_ID_pair_tags_1)
		/sizeof(asn_DEF_UE_S1AP_ID_pair_tags_1[0]), /* 1 */
	asn_DEF_UE_S1AP_ID_pair_tags_1,	/* Same as above */
	sizeof(asn_DEF_UE_S1AP_ID_pair_tags_1)
		/sizeof(asn_DEF_UE_S1AP_ID_pair_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UE_S1AP_ID_pair_1,
	2,	/* Elements count */
	&asn_SPC_UE_S1AP_ID_pair_specs_1	/* Additional specs */
};

