/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_EUTRAN_CGI_H_
#define	_EUTRAN_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNidentity.h"
#include "CellIdentity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EUTRAN-CGI */
typedef struct EUTRAN_CGI {
	PLMNidentity_t	 pLMNidentity;
	CellIdentity_t	 cell_ID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_CGI;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_CGI_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRAN_CGI_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRAN_CGI_H_ */
#include <asn_internal.h>
