/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_HandoverCommand_IEs_H_
#define	_HandoverCommand_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "ENUB-Item.h"
#include "HandoverType-Item.h"
#include "E-RABSubjecttoDataForwardingList-Item.h"
#include "Target-To-Source-TContainer-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HandoverCommand-IEs */
typedef struct HandoverCommand_IEs {
	MME_Item_t	 mme;
	ENUB_Item_t	 enub;
	HandoverType_Item_t	 type;
	E_RABSubjecttoDataForwardingList_Item_t	 forwardList;
	Target_To_Source_TContainer_Item_t	 container;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverCommand_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverCommand_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_HandoverCommand_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_HandoverCommand_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverCommand_IEs_H_ */
#include <asn_internal.h>
