/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_InitialContextSetupRequest_IEs_H_
#define	_InitialContextSetupRequest_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "ENUB-Item.h"
#include "UE-Aggregate-Maxbitrate-Item.h"
#include "E-RABToBeSetupListCtxtSUReq-Item.h"
#include "UESecurityCapabilities-Item.h"
#include "SecurityKey-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitialContextSetupRequest-IEs */
typedef struct InitialContextSetupRequest_IEs {
	MME_Item_t	 mme;
	ENUB_Item_t	 enub;
	UE_Aggregate_Maxbitrate_Item_t	 bitrate;
	E_RABToBeSetupListCtxtSUReq_Item_t	 sureq;
	UESecurityCapabilities_Item_t	 secCap;
	SecurityKey_Item_t	 secKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitialContextSetupRequest_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitialContextSetupRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_InitialContextSetupRequest_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_InitialContextSetupRequest_IEs_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _InitialContextSetupRequest_IEs_H_ */
#include <asn_internal.h>
