/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_InitialUEMessage_IEs_H_
#define	_InitialUEMessage_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ENUB-Item.h"
#include "NAS-Item.h"
#include "TAI-Item.h"
#include "EUTRAN-Item.h"
#include "RRC-Establishment-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitialUEMessage-IEs */
typedef struct InitialUEMessage_IEs {
	ENUB_Item_t	 enub;
	NAS_Item_t	 nas;
	TAI_Item_t	 tai;
	EUTRAN_Item_t	 eutran;
	RRC_Establishment_Item_t	 rrc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitialUEMessage_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitialUEMessage_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_InitialUEMessage_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_InitialUEMessage_IEs_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _InitialUEMessage_IEs_H_ */
#include <asn_internal.h>
