/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_S1AP_PDU_H_
#define	_S1AP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1AP-PDU-Types.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S1AP-PDU */
typedef struct S1AP_PDU {
	S1AP_PDU_Types_t	 type;
	long	 msgType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_PDU_H_ */
#include <asn_internal.h>
