/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_S1AP_PDU_Types_H_
#define	_S1AP_PDU_Types_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitiatingMessage.h"
#include "SuccessfulOutcome.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_PDU_Types_PR {
	S1AP_PDU_Types_PR_NOTHING,	/* No components present */
	S1AP_PDU_Types_PR_initiatingMessage,
	S1AP_PDU_Types_PR_successfulOutcome
} S1AP_PDU_Types_PR;

/* S1AP-PDU-Types */
typedef struct S1AP_PDU_Types {
	S1AP_PDU_Types_PR present;
	union S1AP_PDU_Types_u {
		InitiatingMessage_t	 initiatingMessage;
		SuccessfulOutcome_t	 successfulOutcome;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_PDU_Types_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_PDU_Types;
extern asn_CHOICE_specifics_t asn_SPC_S1AP_PDU_Types_specs_1;
extern asn_TYPE_member_t asn_MBR_S1AP_PDU_Types_1[2];
extern asn_per_constraints_t asn_PER_type_S1AP_PDU_Types_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_PDU_Types_H_ */
#include <asn_internal.h>
