/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_TargetRNC_ID_H_
#define	_TargetRNC_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LAI.h"
#include "RNC-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TargetRNC-ID */
typedef struct TargetRNC_ID {
	LAI_t	 lAI;
	RNC_ID_t	 rNC_ID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetRNC_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetRNC_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_TargetRNC_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargetRNC_ID_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TargetRNC_ID_H_ */
#include <asn_internal.h>
