/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_UE_Aggregate_Maxbitrate_H_
#define	_UE_Aggregate_Maxbitrate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BitRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-Aggregate-Maxbitrate */
typedef struct UE_Aggregate_Maxbitrate {
	BitRate_t	 ue_Aggregate_MaximumBitRateDL;
	BitRate_t	 ue_Aggregate_MaximumBitRateUL;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Aggregate_Maxbitrate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Aggregate_Maxbitrate;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_Aggregate_Maxbitrate_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_Aggregate_Maxbitrate_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_Aggregate_Maxbitrate_H_ */
#include <asn_internal.h>
