/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Structures"
 * 	found in "../asn1_schema/structures.asn"
 */

#ifndef	_UE_S1AP_ID_pair_H_
#define	_UE_S1AP_ID_pair_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-UE-S1AP-ID.h"
#include "ENB-UE-S1AP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-S1AP-ID-pair */
typedef struct UE_S1AP_ID_pair {
	MME_UE_S1AP_ID_t	 mme;
	ENB_UE_S1AP_ID_t	 enub;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_S1AP_ID_pair_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_S1AP_ID_pair;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_S1AP_ID_pair_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_S1AP_ID_pair_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_S1AP_ID_pair_H_ */
#include <asn_internal.h>
