/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_UeContextReleaseRequest_IEs_H_
#define	_UeContextReleaseRequest_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MME-Item.h"
#include "ENUB-Item.h"
#include "Cause-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UeContextReleaseRequest-IEs */
typedef struct UeContextReleaseRequest_IEs {
	MME_Item_t	 mme;
	ENUB_Item_t	 enub;
	Cause_Item_t	 cause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UeContextReleaseRequest_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UeContextReleaseRequest_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UeContextReleaseRequest_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UeContextReleaseRequest_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UeContextReleaseRequest_IEs_H_ */
#include <asn_internal.h>
