/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1_schema/messages.asn"
 */

#ifndef	_UeContextReleaseCommand_IEs_H_
#define	_UeContextReleaseCommand_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-S1AP-IDs-Item.h"
#include "Cause-Item.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UeContextReleaseCommand-IEs */
typedef struct UeContextReleaseCommand_IEs {
	UE_S1AP_IDs_Item_t	 s1ap;
	Cause_Item_t	 cause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UeContextReleaseCommand_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UeContextReleaseCommand_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UeContextReleaseCommand_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UeContextReleaseCommand_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UeContextReleaseCommand_IEs_H_ */
#include <asn_internal.h>
